Some new newbs files
namelivia/qmk_firmware pull request #2
Opened 2019-10-15 18:58 UTC by namelivia

Adds the whole newbie guide translated to Spanish.

2019-10-15 19:00 UTC, namelivia commented
I couldn't add @kbravh as a reviewer, so I'll wait if he can add himsef.

2019-10-16 11:38 UTC, kbravh requested changes
Encontré algunos errores, pero casi está listo!

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_building_firmware.md
> +Ahora que jas configurado tu entorno de construcción estas listo para empezar a construir firmwares personalizados. Para esta sección de la guía alternaremos entre 3 programas - tu gestor de ficheros
```suggestion
Ahora que has configurado tu entorno de construcción estas listo para empezar a construir firmwares personalizados. Para esta sección de la guía alternaremos entre 3 programas - tu gestor de ficheros, tu editor de texto , y tu ventana de terminal. Manten los 3 abiertos hasta que hayas acabado y estés contento con el firmware de tu teclado.
```

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_building_firmware.md
> +Esta línea indica el comienzo del listado de Capas. Debajo encontrarás líenas que contienen o bien `LAYOUT` o `KEYMAP`, y estas líneas indican el comienzo de una capa. Debajo de esa línea está la lis
```suggestion
Esta línea indica el comienzo del listado de Capas. Debajo encontrarás líneas que contienen o bien `LAYOUT` o `KEYMAP`, y estas líneas indican el comienzo de una capa. Debajo de esa línea está la lista de teclas que pertenecen a esa capa concreta.
```

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_building_firmware.md
> +!> Cuando estés editando tu fichero de keymap ten cuidado con no añadir ni eliminar ninguna coma. Si lo haces el firmware dejarlá de compilar y puede no ser fácil averiguar dónde está la coma faltant
```suggestion
!> Cuando estés editando tu fichero de keymap ten cuidado con no añadir ni eliminar ninguna coma. Si lo haces el firmware dejará de compilar y puede no ser fácil averiguar dónde está la coma faltante o sobrante.
```

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_building_firmware_configurator.md
> +# QMK Configurator
Debemos cambiar CMK Configurator => Configurador QMK como en el resto del documento?

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_building_firmware_configurator.md
> +Elige el layout the mejor represente el keymap que quieres crear. Algunos teclados no tienen suficientes layouts o layouts correctos definidos aún. Serán soportados en el futuro.
```suggestion
Elige el layout que mejor represente el keymap que quieres crear. Algunos teclados no tienen suficientes layouts o layouts correctos definidos aún. Serán soportados en el futuro. 
```

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_building_firmware_configurator.md
> +Cuando estes satisfecho con un teclado o quieres trabajar en el después, pulsa el botón `Exportar Keymap`. Guardára tu keymap con el nombre que elijas seguido de .json.
```suggestion
Cuando estés satisfecho con un teclado o quieres trabajar en el después, pulsa el botón `Exportar Keymap`. Guardára tu keymap con el nombre que elijas seguido de .json. 
```

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_building_firmware_configurator.md
> +Entonces podrás cargar este fichero .json en el futuro pulsando el botón `Import Keymap`.
```suggestion
Entonces podrás cargar este fichero .json en el futuro pulsando el botón `Importar Keymap`. 
```

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_building_firmware_configurator.md
> +Por favor, revisa las otras capas de tu keymap para asegurarte de que no hay telcas aleatorias presentes.
```suggestion
Por favor, revisa las otras capas de tu keymap para asegurarte de que no hay teclas aleatorias presentes. 
```

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_building_firmware_configurator.md
> +Siempre aceptamos peticiones de clientes y reportes de bug. Por favor, indicalos en [qmk_configurator](https://github.com/qmk/qmk_configurator/issues)
```suggestion
Siempre aceptamos peticiones de clientes y reportes de bug. Por favor, indícalos en [qmk_configurator](https://github.com/qmk/qmk_configurator/issues)
```

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_flashing.md
> +Puedes encontrar más información sobre bootloaders en la página [Instrucciones de flaseado e información de Bootloader](flashing.md).
```suggestion
Puedes encontrar más información sobre bootloaders en la página [Instrucciones de flasheado e información de Bootloader](flashing.md). 
```

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_flashing.md
> +Una vez que lo haga, querrás reinicar el controlador.  Debería entonces mostrar una información de salira similar a esta:
```suggestion
Una vez que lo haga, querrás reinicar el controlador.  Debería entonces mostrar una información de salida similar a esta: 
```

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_flashing.md
> +* `:dfu-util-split-left` - Flashea el firmware normal, gual que la opción por defecto (`:dfu-util`). Sin embargo, también flashea el fichero EEPROM "Lado Izquierdo" para teclados divididos.
```suggestion
* `:dfu-util-split-left` - Flashea el firmware normal, igual que la opción por defecto (`:dfu-util`). Sin embargo, también flashea el fichero EEPROM "Lado Izquierdo" para teclados divididos.
```

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_flashing.md
> +* `:dfu-util-split-right` - Flashea el firmware normal, gual que la opción por defecto (`:dfu-util`). Sin embargo, también flashea el fichero EEPROM "Lado Derecho" para teclados divididos.
```suggestion
* `:dfu-util-split-right` - Flashea el firmware normal, igual que la opción por defecto (`:dfu-util`). Sin embargo, también flashea el fichero EEPROM "Lado Derecho" para teclados divididos.
```

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_testing_debugging.md
> +Cuando estés portando, o intentando diagnosticar problemas en la pcb, puwdw ser útil saber si la pulsación de una tecla es escaneada correctamente. Para hablitar la información de registro en este es
```suggestion
Cuando estés portando, o intentando diagnosticar problemas en la pcb, puede ser útil saber si la pulsación de una tecla es escaneada correctamente. Para hablitar la información de registro en este escenario, añade el siguiente código al `keymap.c` de tus keymaps
```

2019-10-16 11:38 UTC, kbravh commented on docs/es/newbs_testing_debugging.md
> +### ¿Que posición en la matriz tiene esta plusación de tecla?
```suggestion
### ¿Que posición en la matriz tiene esta pulsación de tecla?
```

2019-10-17 06:17 UTC, namelivia commented on docs/es/newbs_building_firmware_configurator.md
> +# QMK Configurator
Sí, lo he cambiado ya. Gracias!

2019-10-17 06:17 UTC, merged